### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by nedbat** [diazona/setuptools-pyproject-migration#100]
I'm not sure what's different about my environment:

```
% pipx install setuptools-pyproject-migration
  installed package setuptools-pyproject-migration 0.1.0, installed using Python 3.11.5
  These apps are now globally available
    - setup-to-pyproject
done! ✨ 🌟 ✨

% setup-to-pyproject
Traceback (most recent call last):
  File "/Users/nbatchelder/.local/bin/setup-to-pyproject", line 5, in <module>
    from setuptools_pyproject_migration.cli import main
  File "/Users/nbatchelder/.local/pipx/venvs/setuptools-pyproject-migration/lib/python3.11/site-packages/setuptools_pyproject_migration/__init__.py", line 7, in <module>
    from packaging.specifiers import SpecifierSet
ModuleNotFoundError: No module named 'packaging'
```

**Comment by diazona** [comment]
Ooh, good catch, thanks for reporting! (congrats on the first external issue report 🎉) We probably just forgot to list a dependency. We'll definitely fix it - or feel free to submit a PR if you want, no obligation though.

Would you mind sharing the exact list of packages that got installed for you? (`pipx runpip setuptools-pyproject-migration freeze`) Just in case it's relevant for version info or something.

**Comment by nedbat** [comment]
```
% pipx runpip setuptools-pyproject-migration freeze
Parsley==1.3
pep508-parser==2019.3
setuptools-pyproject-migration==0.1.0
tomlkit==0.12.1
typing_extensions==4.8.0
```

**Comment by sjlongland** [comment]
On Gentoo, the missing module is provided by `dev-python/packaging:0` … homepage: https://pypi.org/project/packaging/

`qdepends` tells me `dev-python/setuptools` is one of the packages that depends on it.  `setuptools` is explicitly listed as a dependency, so not quite sure how that got missed.

**Comment by sjlongland** [comment]
Can reproduce:

```
RC=0 stuartl@rikishi ~/projects/wicen/rfid/aioax25 $ setup-to-pyproject 
Traceback (most recent call last):
  File "/home/stuartl/.local/bin/setup-to-pyproject", line 5, in <module>
    from setuptools_pyproject_migration.cli import main
  File "/home/stuartl/.local/pipx/venvs/setuptools-pyproject-migration/lib/python3.11/site-packages/setuptools_pyproject_migration/__init__.py", line 7, in <module>
    from packaging.specifiers import SpecifierSet
ModuleNotFoundError: No module named 'packaging'
```

**Comment by sjlongland** [comment]
The very strange thing, `pip` in the virtual environment _does_ see `setuptools`:

```
RC=0 stuartl@rikishi ~/projects/wicen/rfid/aioax25 $ pipx runpip setuptools-pyproject-migration freeze
Parsley==1.3
pep508-parser==2019.3
setuptools-pyproject-migration==0.1.0
tomlkit==0.12.1
typing_extensions==4.8.0
RC=0 stuartl@rikishi ~/projects/wicen/rfid/aioax25 $ pipx runpip setuptools-pyproject-migration install setuptools
Requirement already satisfied: setuptools in /home/stuartl/.local/pipx/shared/lib/python3.11/site-packages (68.2.2)
```

`pipx` bug perhaps?

**Comment by diazona** [comment]
Maybe `pip freeze` omits setuptools from the listing? I remember that there is at least one `pip` command that does that but I thought it was `list` not `freeze`.

**Comment by sjlongland** [comment]
I bypassed `pipx` and installed it with `pip3 install --user .` from the `git` work directory, and it did work… so it would appear `pipx` does something strange with its environment.

**Comment by sjlongland** [comment]
```
RC=0 stuartl@rikishi ~/projects/setuptools-pyproject-migration/work $ pipx runpip setuptools-pyproject-migration list
Package                        Version
------------------------------ -------
Parsley                        1.3
pep508-parser                  2019.3
pip                            23.2.1
setuptools                     68.2.2
setuptools-pyproject-migration 0.1.0
tomlkit                        0.12.1
typing_extensions              4.8.0
wheel                          0.41.2
```

**Comment by sjlongland** [comment]
@nedbat Can you try running `pipx runpip setuptools-pyproject-migration install packaging` then re-try `setup-to-pyproject`?

I think `pipx` somehow manages to omit the `packaging` module despite it being a `setuptools` dependency.

**Comment by diazona** [comment]
I suspect it's more likely that it just used the `packaging` from your system Python. pipx doesn't do much more than create a virtual environment and install the package into it, as far as I remember. (If you try doing that manually, my guess is you'll see it fail as well)

**Comment by nedbat** [comment]
@sjlongland I ran that command and now things run properly.  Why not add `packaging` to your list of dependencies?  Your code imports from it, so you need it, so it should be in your own dependencies.

**Comment by diazona** [comment]
BTW now that I think about it, I believe `setuptools` vendors `packaging`, making a private copy that only `setuptools` itself knows how to use. It's possible that the Gentoo devs extracted that vendored dependency out and made a custom build of `setuptools` that uses the system `packaging`. If so, obviously we cannot count on that in general, so I guess we need to explicitly add a dependency on `packaging`. (which TBH I thought we did? I'm on my phone so can't check while writing this comment)

**Comment by diazona** [comment]
@nedbat For the record, this is not a case where we expected `packaging` to just randomly be there or we had a reason not to list it as a dependency. It should have been listed. We just made a mistake. Somehow it escaped the notice of both whoever wrote the PR that added that import statement and whoever reviewed it, as well as not getting caught in automated testing.

**Comment by sjlongland** [comment]
@diazona Have a look at PR #101 :-)
