### ISSUE TITLE
Reduce frequency of pre-commit autoupdates

### ISSUE THREAD

**Issue by diazona** [diazona/setuptools-pyproject-migration#109]
Right now every week we get a PR from the pre-commit CI service that tries to update all our hooks, including updating the ruff hook to a version which is incompatible with Python 3.6. We probably don't need weekly updates to this configuration, as there are basically never serious problems with the hooks that require an immediate update, so this issue would entail changing it to monthly or quarterly to reduce how often we have to deal with those PRs. (I've been meaning to make that change for a long time but never got around to it, just out of laziness.)

Or we could stop using the pre-commit.ci service entirely and just implement our own pre-commit workflow in this repo. That would let us avoid automatic updates entirely. (In fact we could even write our own separate logic to handle them, although that would be outside the scope of this issue.)

**Comment by sjlongland** [comment]
I wonder if there's a disadvantage to just running it purely through Github actions.  That avoids tying up resources in two places by consolidating it all within Github actions runners.

**Comment by diazona** [comment]
From the research I did when we originally set it up, I seem to remember that the only difference between pre-commit.ci and a custom action was the automatic updates. At least the only difference I could figure out. (Well, aside from the matter of whose runners get used) So I kind of suspect there is no disadvantage - but definitely worth double-checking.

**Comment by datatalking** [comment]
If I've understood what your goal is I concur with @diazona and want to offer @sjlongland some assurance that GitHub ci is or was helpful for my team.

I could take a look at this, GitHub Ci does have a few advantages and as long as we don't exceed the monthly minutes of time or cycles it can be a rather simple setup.

We might benefit from having a 'we update schedule' arranged and on the calendar to have people review the code and give it a thumbs up for submitting to GitHub.

Thoughts?

**Comment by diazona** [comment]
Thanks for chiming in!

Personally, my goal is just to avoid having to manually modify a PR from pre-commit.ci every week. I mean, we do want to keep compatibility with Python 3.6 (since we know some developers who may want to use this package are painfully out of date with their Python upgrades), which means rejecting the automatic updates to the ruff hook. But I'm ambivalent about how exactly that is accomplished; whether by reducing the frequency of updates, or by building some automation to revert the change to the ruff pre-commit hook every time, or by dropping pre-commit.ci and running pre-commit on GHA. (Though I have come around to the idea that automatic updates to most hooks are a good thing.)

Reducing the frequency is the simplest approach, of course, and in general simplicity is nice when there isn't a reason to do otherwise, but I think if you're willing to do the work on this, you can more or less make your own choice about which approach to take.

**Comment by diazona** [comment]
I'm just going to fix this for now by dropping the update frequency to monthly. It's annoying enough to deal with these PRs every week. We can still move away from using autoupdates entirely if we want to in the future, but that would be a separate issue.
