### ISSUE TITLE
Add Stuart as a collaborator on ReadTheDocs

### ISSUE THREAD

**Issue by diazona** [diazona/setuptools-pyproject-migration#19]
@sjlongland if you create an account on [ReadTheDocs](https://readthedocs.org/) and let me know your username, I'll add you as a maintainer of the project's documentation there.

**Comment by sjlongland** [comment]
Yep, just done: `sjlongland` there too.

**Comment by diazona** [comment]
:cool: An invitation should be coming your way any moment now. Feel free to close this when you get it.

**Comment by sjlongland** [comment]
Yep, done and dusted. :-)
