### ISSUE TITLE
Enable pre-commit.ci

### ISSUE THREAD

**Issue by diazona** [diazona/setuptools-pyproject-migration#38]
https://pre-commit.ci/ is a service that automatically runs pre-commit on all pull requests and can optionally automatically apply any necessary fixes, as well as automatically proposing updates to the hook versions in the pre-commit configuration.

@sjlongland what do you think, should we enable it? I don't think there's much to do except log in on the pre-commit.ci website and register the project.

**Comment by sjlongland** [comment]
Seems like a good idea.  We can give it a try.

**Comment by diazona** [comment]
OK done :+1: at least I think so... we'll see if it works. If we have trouble we have some [configuration options](https://pre-commit.ci/#configuration) to tune (although I'm not bothering to set them now, more out of laziness than anything else :stuck_out_tongue:), and/or we can switch to the ["lite version"](https://pre-commit.ci/lite.html) which runs as a GHA workflow instead of a third-party service.
